[build]
  command = "npm run build && npm run postbuild"
  publish = "build"

# Serve all .js files with the correct MIME type.
[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "text/javascript"

# Serve all .jsx files with the correct MIME type.
[[headers]]
  for = "/*.jsx"
  [headers.values]
    Content-Type = "text/javascript"

# For single-page applications, redirect all paths to index.html.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
